import React from 'react';
import { useLocation, Link, useNavigate } from 'react-router-dom';
import { CheckCircle, XCircle, AlertTriangle, ArrowLeft, BarChart2 } from 'lucide-react';

export default function AnalysisResult() {
  const location = useLocation();
  const navigate = useNavigate();
  const result = location.state?.result;

  if (!result) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[50vh]">
        <h2 className="text-xl font-bold text-white mb-4">No result found</h2>
        <button onClick={() => navigate('/dashboard')} className="btn-secondary">Back to Dashboard</button>
      </div>
    );
  }

  const isFake = result.prediction !== 'REAL';
  const scoreColor = isFake ? 'text-danger' : 'text-secondary';
  const Icon = isFake ? XCircle : CheckCircle;

  return (
    <div className="max-w-4xl mx-auto px-4 py-12">
      <Link to="/dashboard" className="inline-flex items-center text-gray-400 hover:text-white mb-8 transition-colors">
        <ArrowLeft className="h-4 w-4 mr-2" /> Back to Dashboard
      </Link>

      <div className="glass-card overflow-hidden animate-in fade-in slide-in-from-bottom-4 duration-500">
        {/* Header Banner */}
        <div className={`p-8 flex items-center justify-between border-b ${isFake ? 'bg-danger/10 border-danger/20' : 'bg-secondary/10 border-secondary/20'}`}>
          <div className="flex items-center space-x-4">
            <Icon className={`h-12 w-12 ${scoreColor}`} />
            <div>
              <p className="text-sm font-medium text-gray-400 uppercase tracking-wider">{result.type} Analysis Result</p>
              <h2 className={`text-3xl font-bold ${scoreColor}`}>
                {result.prediction}
              </h2>
            </div>
          </div>
          <div className="text-right">
            <p className="text-sm font-medium text-gray-400 uppercase tracking-wider mb-1">Confidence Score</p>
            <div className="flex items-baseline space-x-1">
              <span className={`text-4xl font-black ${scoreColor}`}>{result.confidence}</span>
              <span className="text-xl text-gray-500">%</span>
            </div>
          </div>
        </div>

        {/* Content Details */}
        <div className="p-8">
          <div className="mb-8 pb-8 border-b border-white/10">
            <h3 className="text-lg font-medium text-white mb-2">Analyzed Content</h3>
            <p className="text-gray-400 truncate bg-surface/50 p-4 rounded-lg border border-white/5 font-mono text-sm">
              {result.fileNameOrContent}
            </p>
          </div>

          <h3 className="text-lg font-medium text-white mb-6 flex items-center">
            <BarChart2 className="h-5 w-5 mr-2 text-primary" />
            Detailed Breakdown
          </h3>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {Object.entries(result.resultDetails || {}).map(([key, value]) => (
              <div key={key} className="bg-surface/50 rounded-xl p-5 border border-white/5 hover:border-white/10 transition-colors">
                <p className="text-sm font-medium text-gray-400 uppercase tracking-wider mb-2">
                  {key.replace(/_/g, ' ')}
                </p>
                <div className="flex items-center justify-between">
                  <div className="w-full bg-background rounded-full h-2.5 mr-4 overflow-hidden">
                    <div 
                      className="bg-gradient-to-r from-primary to-blue-400 h-2.5 rounded-full" 
                      style={{ width: value }}
                    ></div>
                  </div>
                  <span className="text-white font-bold">{value}</span>
                </div>
              </div>
            ))}
          </div>

          <div className="mt-10 p-4 rounded-lg bg-surface flex items-start space-x-3 border border-white/5">
            <AlertTriangle className="h-5 w-5 text-warning flex-shrink-0 mt-0.5" />
            <p className="text-sm text-gray-400 leading-relaxed">
              This result was generated by TruthLens AI. While we strive for accuracy, AI models can occasionally produce false positives or negatives. We recommend verifying critical information across multiple trusted sources.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
