import React, { useCallback, useState } from 'react';
import { useDropzone } from 'react-dropzone';
import { UploadCloud, Image as ImageIcon, Loader2, AlertCircle, Sparkles, CheckSquare, Eye, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import api from '../../api';

export default function ImageModule() {
  const [file, setFile] = useState(null);
  const [previewUrl, setPreviewUrl] = useState('');
  const [imageMeta, setImageMeta] = useState(null);
  const [loading, setLoading] = useState(false);
  const [scanStep, setScanStep] = useState(0);
  const [error, setError] = useState('');
  const navigate = useNavigate();

  const scanSteps = [
    'Parsing Quantization Tables & Camera EXIF...',
    'Generating Error Level Analysis (ELA) Delta Map...',
    'Evaluating Latent Diffusion & GAN High-Frequency Fingerprints...',
    'Synthesizing Forensic Confidence Report...'
  ];

  const onDrop = useCallback((acceptedFiles) => {
    if (acceptedFiles?.length > 0) {
      const selected = acceptedFiles[0];
      setFile(selected);
      setError('');
      
      const objectUrl = URL.createObjectURL(selected);
      setPreviewUrl(objectUrl);

      // Extract image dimensions
      const img = new Image();
      img.onload = () => {
        setImageMeta({
          width: img.naturalWidth,
          height: img.naturalHeight,
          size: (selected.size / 1024).toFixed(1) + ' KB'
        });
      };
      img.src = objectUrl;
    }
  }, []);

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop,
    accept: {
      'image/*': ['.jpeg', '.jpg', '.png', '.webp', '.heic']
    },
    maxFiles: 1,
    maxSize: 50 * 1024 * 1024 // 50MB
  });

  const handleClear = () => {
    setFile(null);
    setPreviewUrl('');
    setImageMeta(null);
    setError('');
  };

  const handleAnalyze = async () => {
    if (!file) {
      setError('Please upload an image to analyze.');
      return;
    }

    setLoading(true);
    setError('');
    setScanStep(0);

    // Simulate multi-stage progress ticker
    const interval = setInterval(() => {
      setScanStep((prev) => (prev < scanSteps.length - 1 ? prev + 1 : prev));
    }, 650);

    const formData = new FormData();
    formData.append('file', file);
    formData.append('type', 'IMAGE');

    try {
      const res = await api.post('/analysis', formData, {
        headers: {
          'Content-Type': 'multipart/form-data'
        }
      });
      clearInterval(interval);
      navigate('/results', { state: { result: res.data } });
    } catch (err) {
      clearInterval(interval);
      setError(err.response?.data?.message || 'Forensic analysis failed. Please try again.');
      setLoading(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto py-6">
      <div className="mb-8 animate-in fade-in slide-in-from-top-4">
        <div className="inline-flex items-center space-x-2 bg-purple-50 text-purple-600 px-3 py-1 rounded-full text-xs font-bold mb-3">
          <Sparkles className="h-3.5 w-3.5" />
          <span>Error Level Analysis (ELA) + Latent Diffusion Detection</span>
        </div>
        <h1 className="text-3xl font-black text-dark tracking-tight mb-2">AI Image Analysis & Forensics</h1>
        <p className="text-sm text-gray-500">Detect if a photo was generated by Midjourney, Stable Diffusion, DALL-E, or manipulated in Photoshop.</p>
      </div>

      {error && (
        <div className="mb-6 p-4 bg-danger/10 border border-danger/20 rounded-xl flex items-center text-danger max-w-3xl">
          <AlertCircle className="h-5 w-5 mr-2.5 shrink-0" />
          <p className="text-sm font-medium">{error}</p>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8">
        {/* Upload & Preview Card */}
        <div className="lg:col-span-2">
          {!previewUrl ? (
            <div 
              {...getRootProps()} 
              className={`glass-card p-12 flex flex-col items-center justify-center text-center cursor-pointer border-2 border-dashed transition-all duration-300 min-h-[340px] ${
                isDragActive ? 'border-primary bg-primary/5' : 'border-gray-300 hover:border-primary/50 hover:bg-gray-50/50'
              }`}
            >
              <input {...getInputProps()} />
              <div className="bg-purple-50 p-4 rounded-2xl text-purple-600 mb-5 shadow-xs">
                <UploadCloud className="h-10 w-10" />
              </div>
              
              {isDragActive ? (
                <p className="text-lg font-bold text-primary mb-1">Drop the image here to scan</p>
              ) : (
                <>
                  <p className="text-lg font-bold text-dark mb-1">
                    Drag and drop an image here
                  </p>
                  <p className="text-sm text-gray-500 mb-4">or click to browse from your device</p>
                </>
              )}
              <span className="text-xs font-semibold text-gray-400 px-3 py-1 bg-gray-100 rounded-full">
                JPG, PNG, WEBP, HEIC · Up to 50 MB
              </span>
            </div>
          ) : (
            <div className="glass-card p-6">
              <div className="flex items-center justify-between mb-4 pb-3 border-b border-gray-100">
                <div className="flex items-center space-x-2 text-dark font-bold text-sm">
                  <Eye className="h-4 w-4 text-purple-600" />
                  <span>Image Inspection Preview</span>
                </div>
                {!loading && (
                  <button 
                    onClick={handleClear}
                    className="text-xs text-gray-400 hover:text-danger flex items-center space-x-1 cursor-pointer"
                  >
                    <X className="h-3.5 w-3.5" />
                    <span>Change Image</span>
                  </button>
                )}
              </div>

              <div className="relative rounded-xl overflow-hidden bg-slate-900 flex items-center justify-center max-h-[340px] border border-gray-200">
                <img 
                  src={previewUrl} 
                  alt="Upload preview" 
                  className="max-h-[320px] w-auto object-contain rounded-lg"
                />
              </div>

              {imageMeta && (
                <div className="mt-4 grid grid-cols-3 gap-3 text-center">
                  <div className="bg-gray-50 p-2.5 rounded-xl border border-gray-100">
                    <p className="text-[10px] uppercase font-bold text-gray-400">File Name</p>
                    <p className="text-xs font-bold text-dark truncate">{file.name}</p>
                  </div>
                  <div className="bg-gray-50 p-2.5 rounded-xl border border-gray-100">
                    <p className="text-[10px] uppercase font-bold text-gray-400">Resolution</p>
                    <p className="text-xs font-bold text-dark">{imageMeta.width} × {imageMeta.height} px</p>
                  </div>
                  <div className="bg-gray-50 p-2.5 rounded-xl border border-gray-100">
                    <p className="text-[10px] uppercase font-bold text-gray-400">File Size</p>
                    <p className="text-xs font-bold text-dark">{imageMeta.size}</p>
                  </div>
                </div>
              )}

              {loading && (
                <div className="mt-6 p-4 rounded-xl bg-purple-50 border border-purple-100 animate-in fade-in">
                  <div className="flex items-center space-x-3 mb-2">
                    <Loader2 className="h-5 w-5 text-purple-600 animate-spin" />
                    <p className="text-sm font-bold text-purple-900">{scanSteps[scanStep]}</p>
                  </div>
                  <div className="w-full bg-purple-200/50 rounded-full h-1.5 overflow-hidden">
                    <div 
                      className="bg-purple-600 h-1.5 rounded-full transition-all duration-500" 
                      style={{ width: `${((scanStep + 1) / scanSteps.length) * 100}%` }}
                    />
                  </div>
                </div>
              )}

              <div className="mt-6 flex justify-end">
                <button
                  onClick={handleAnalyze}
                  disabled={loading || !file}
                  className="btn-primary space-x-2 bg-purple-600 hover:bg-purple-700 shadow-purple-500/20"
                >
                  {loading ? (
                    <>
                      <Loader2 className="h-4 w-4 animate-spin" />
                      <span>Verifying Image Forensics...</span>
                    </>
                  ) : (
                    <>
                      <Sparkles className="h-4 w-4" />
                      <span>Run Forensic Analysis</span>
                    </>
                  )}
                </button>
              </div>
            </div>
          )}
        </div>

        {/* Forensic Checks Overview Card */}
        <div className="space-y-6">
          <div className="glass-card p-6">
            <h3 className="text-sm font-bold text-dark uppercase tracking-wider mb-4">Enabled Forensic Pipelines</h3>
            
            <div className="space-y-4 text-xs">
              <div className="flex items-start space-x-3">
                <div className="h-2 w-2 rounded-full bg-purple-500 mt-1.5 shrink-0" />
                <div>
                  <p className="font-bold text-dark">Error Level Analysis (ELA)</p>
                  <p className="text-gray-500">Generates 90% JPEG re-quantization error map to locate spliced or inpainted pixels.</p>
                </div>
              </div>

              <div className="flex items-start space-x-3">
                <div className="h-2 w-2 rounded-full bg-purple-500 mt-1.5 shrink-0" />
                <div>
                  <p className="font-bold text-dark">GAN & Diffusion Fingerprint</p>
                  <p className="text-gray-500">Detects subtle frequency artifacts produced by Midjourney v5/v6, SDXL, and DALL-E 3.</p>
                </div>
              </div>

              <div className="flex items-start space-x-3">
                <div className="h-2 w-2 rounded-full bg-purple-500 mt-1.5 shrink-0" />
                <div>
                  <p className="font-bold text-dark">EXIF Sensor Profile Validation</p>
                  <p className="text-gray-500">Checks for camera hardware tags (Make/Model) vs AI generator software stamps.</p>
                </div>
              </div>
            </div>
          </div>

          <div className="glass-card p-5 bg-gradient-to-br from-purple-50/50 to-white border-purple-100">
            <p className="text-xs font-bold text-purple-900 mb-1">Forensics Tip</p>
            <p className="text-[11px] text-purple-700 leading-relaxed">
              For best accuracy, upload uncompressed original images directly from source cameras or platforms without resizing.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
