import React, { useCallback, useState } from 'react';
import { useDropzone } from 'react-dropzone';
import { 
  Video, Image as ImageIcon, FileText, UploadCloud, Loader2, 
  AlertCircle, Sparkles, Eye, X, ChevronDown 
} from 'lucide-react';
import { useNavigate, Link } from 'react-router-dom';
import api from '../../api';

export default function ImageModule() {
  const [file, setFile] = useState(null);
  const [previewUrl, setPreviewUrl] = useState('');
  const [imageMeta, setImageMeta] = useState(null);
  const [loading, setLoading] = useState(false);
  const [scanStep, setScanStep] = useState(0);
  const [error, setError] = useState('');
  const [showVectors, setShowVectors] = useState(false);
  const navigate = useNavigate();

  const scanSteps = [
    'Parsing Quantization Tables & Camera EXIF...',
    'Generating Error Level Analysis (ELA) Delta Map...',
    'Evaluating Latent Diffusion & GAN High-Frequency Fingerprints...',
    'Synthesizing Forensic Confidence Report...'
  ];

  const onDrop = useCallback((acceptedFiles) => {
    if (acceptedFiles?.length > 0) {
      const selected = acceptedFiles[0];
      setFile(selected);
      setError('');
      
      const objectUrl = URL.createObjectURL(selected);
      setPreviewUrl(objectUrl);

      // Extract image dimensions
      const img = new Image();
      img.onload = () => {
        setImageMeta({
          width: img.naturalWidth,
          height: img.naturalHeight,
          size: (selected.size / 1024).toFixed(1) + ' KB'
        });
      };
      img.src = objectUrl;
    }
  }, []);

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop,
    accept: {
      'image/*': ['.jpeg', '.jpg', '.png', '.webp', '.heic']
    },
    maxFiles: 1,
    maxSize: 50 * 1024 * 1024 // 50MB
  });

  const handleClear = () => {
    setFile(null);
    setPreviewUrl('');
    setImageMeta(null);
    setError('');
  };

  const handleAnalyze = async () => {
    if (!file) {
      setError('Please upload an image to analyze.');
      return;
    }

    setLoading(true);
    setError('');
    setScanStep(0);

    const interval = setInterval(() => {
      setScanStep((prev) => (prev < scanSteps.length - 1 ? prev + 1 : prev));
    }, 650);

    const formData = new FormData();
    formData.append('file', file);
    formData.append('type', 'IMAGE');

    try {
      const res = await api.post('/analysis', formData, {
        headers: {
          'Content-Type': 'multipart/form-data'
        }
      });
      clearInterval(interval);
      navigate('/results', { state: { result: res.data } });
    } catch (err) {
      clearInterval(interval);
      setError(err.response?.data?.message || 'Forensic analysis failed. Please try again.');
      setLoading(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto py-1 sm:py-6">
      {/* Module Switcher Header Bar */}
      <div className="flex items-center space-x-1 sm:space-x-2 p-1.5 bg-gray-100/90 rounded-2xl mb-4 sm:mb-6 overflow-x-auto no-scrollbar">
        <Link 
          to="/modules/video" 
          className="flex-1 min-w-[95px] flex items-center justify-center space-x-1.5 py-2 px-3 rounded-xl text-xs font-bold transition-all text-gray-500 hover:text-dark"
        >
          <Video className="h-4 w-4" /> <span>Video</span>
        </Link>
        <Link 
          to="/modules/image" 
          className="flex-1 min-w-[95px] flex items-center justify-center space-x-1.5 py-2 px-3 rounded-xl text-xs font-bold transition-all bg-white text-purple-600 shadow-xs"
        >
          <ImageIcon className="h-4 w-4" /> <span>Image</span>
        </Link>
        <Link 
          to="/modules/news" 
          className="flex-1 min-w-[95px] flex items-center justify-center space-x-1.5 py-2 px-3 rounded-xl text-xs font-bold transition-all text-gray-500 hover:text-dark"
        >
          <FileText className="h-4 w-4" /> <span>News</span>
        </Link>
      </div>

      {/* Title & Banner */}
      <div className="mb-4 sm:mb-8 animate-in fade-in slide-in-from-top-4">
        <div className="inline-flex items-center space-x-1.5 bg-purple-50 text-purple-600 px-2.5 py-1 rounded-full text-[11px] sm:text-xs font-bold mb-2">
          <Sparkles className="h-3.5 w-3.5 shrink-0" />
          <span className="truncate">Error Level Analysis (ELA) + Latent Diffusion Detection</span>
        </div>
        <h1 className="text-xl sm:text-2xl md:text-3xl font-black text-dark tracking-tight mb-1">
          AI Image Analysis & Forensics
        </h1>
        <p className="text-xs sm:text-sm text-gray-500">
          Detect if a photo was generated by Midjourney, Stable Diffusion, DALL-E, or manipulated in Photoshop.
        </p>
      </div>

      {error && (
        <div className="mb-5 p-3 sm:p-4 bg-danger/10 border border-danger/20 rounded-xl flex items-center text-danger max-w-3xl text-xs sm:text-sm">
          <AlertCircle className="h-4 w-4 sm:h-5 sm:w-5 mr-2.5 shrink-0" />
          <p className="font-medium">{error}</p>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 sm:gap-6 mb-8">
        {/* Upload & Preview Card */}
        <div className="lg:col-span-2">
          {!previewUrl ? (
            <div 
              {...getRootProps()} 
              className={`glass-card p-5 sm:p-10 flex flex-col items-center justify-center text-center cursor-pointer border-2 border-dashed transition-all duration-300 min-h-[220px] sm:min-h-[320px] ${
                isDragActive ? 'border-primary bg-primary/5' : 'border-gray-300 hover:border-primary/50 hover:bg-gray-50/50'
              }`}
            >
              <input {...getInputProps()} />
              <div className="bg-purple-50 p-3 sm:p-4 rounded-2xl text-purple-600 mb-3 sm:mb-4 shadow-xs">
                <UploadCloud className="h-7 w-7 sm:h-9 sm:w-9" />
              </div>
              
              {isDragActive ? (
                <p className="text-sm sm:text-base font-bold text-primary mb-1">Drop image here to scan</p>
              ) : (
                <>
                  <p className="text-sm sm:text-base font-bold text-dark mb-1">
                    Tap to select or drop an image
                  </p>
                  <p className="text-xs text-gray-500 mb-3">JPG, PNG, WEBP, HEIC up to 50 MB</p>
                </>
              )}
              <span className="text-[10px] sm:text-xs font-semibold text-gray-400 px-2.5 py-0.5 bg-gray-100 rounded-full">
                Direct Sensor Bitstream Analysis
              </span>
            </div>
          ) : (
            <div className="glass-card p-3.5 sm:p-6">
              <div className="flex items-center justify-between mb-3 pb-2.5 border-b border-gray-100">
                <div className="flex items-center space-x-1.5 text-dark font-bold text-xs sm:text-sm">
                  <Eye className="h-4 w-4 text-purple-600" />
                  <span>Inspection Preview</span>
                </div>
                {!loading && (
                  <button 
                    onClick={handleClear}
                    className="text-xs text-gray-400 hover:text-danger flex items-center space-x-1 cursor-pointer"
                  >
                    <X className="h-3.5 w-3.5" />
                    <span>Change</span>
                  </button>
                )}
              </div>

              <div className="relative rounded-xl overflow-hidden bg-slate-900 flex items-center justify-center max-h-[240px] sm:max-h-[320px] border border-gray-200">
                <img 
                  src={previewUrl} 
                  alt="Upload preview" 
                  className="max-h-[220px] sm:max-h-[300px] w-auto object-contain rounded-lg"
                />
              </div>

              {imageMeta && (
                <div className="mt-3 grid grid-cols-3 gap-1.5 sm:gap-3 text-center">
                  <div className="bg-gray-50 p-2 rounded-xl border border-gray-100">
                    <p className="text-[9px] sm:text-[10px] uppercase font-bold text-gray-400">File Name</p>
                    <p className="text-[11px] sm:text-xs font-bold text-dark truncate">{file.name}</p>
                  </div>
                  <div className="bg-gray-50 p-2 rounded-xl border border-gray-100">
                    <p className="text-[9px] sm:text-[10px] uppercase font-bold text-gray-400">Resolution</p>
                    <p className="text-[11px] sm:text-xs font-bold text-dark truncate">{imageMeta.width}×{imageMeta.height}</p>
                  </div>
                  <div className="bg-gray-50 p-2 rounded-xl border border-gray-100">
                    <p className="text-[9px] sm:text-[10px] uppercase font-bold text-gray-400">Size</p>
                    <p className="text-[11px] sm:text-xs font-bold text-dark truncate">{imageMeta.size}</p>
                  </div>
                </div>
              )}

              {loading && (
                <div className="mt-4 p-3.5 rounded-xl bg-purple-50 border border-purple-100 animate-in fade-in">
                  <div className="flex items-center space-x-2.5 mb-2">
                    <Loader2 className="h-4 w-4 sm:h-5 sm:w-5 text-purple-600 animate-spin shrink-0" />
                    <p className="text-xs sm:text-sm font-bold text-purple-900 truncate">{scanSteps[scanStep]}</p>
                  </div>
                  <div className="w-full bg-purple-200/50 rounded-full h-1.5 overflow-hidden">
                    <div 
                      className="bg-purple-600 h-1.5 rounded-full transition-all duration-500" 
                      style={{ width: `${((scanStep + 1) / scanSteps.length) * 100}%` }}
                    />
                  </div>
                </div>
              )}

              <div className="mt-4 sm:mt-6 flex justify-end">
                <button
                  onClick={handleAnalyze}
                  disabled={loading || !file}
                  className="btn-primary w-full sm:w-auto space-x-2 bg-purple-600 hover:bg-purple-700 shadow-purple-500/20 justify-center py-2.5 sm:py-3 text-xs sm:text-sm font-bold"
                >
                  {loading ? (
                    <>
                      <Loader2 className="h-4 w-4 animate-spin" />
                      <span>Verifying Image Forensics...</span>
                    </>
                  ) : (
                    <>
                      <Sparkles className="h-4 w-4" />
                      <span>Run Forensic Analysis</span>
                    </>
                  )}
                </button>
              </div>
            </div>
          )}
        </div>

        {/* Forensic Checks Overview Card (Collapsible on Mobile) */}
        <div className="space-y-3 sm:space-y-6">
          <div className="glass-card p-4 sm:p-6">
            <button 
              onClick={() => setShowVectors(!showVectors)}
              className="w-full flex items-center justify-between text-left lg:pointer-events-none"
            >
              <h3 className="text-xs sm:text-sm font-bold text-dark uppercase tracking-wider">
                Enabled Pipelines
              </h3>
              <ChevronDown className={`h-4 w-4 text-gray-400 lg:hidden transition-transform ${showVectors ? 'rotate-180' : ''}`} />
            </button>
            
            <div className={`space-y-3 sm:space-y-4 text-xs mt-3 lg:block ${showVectors ? 'block' : 'hidden'}`}>
              <div className="flex items-start space-x-2.5">
                <div className="h-2 w-2 rounded-full bg-purple-500 mt-1.5 shrink-0" />
                <div>
                  <p className="font-bold text-dark">Error Level Analysis (ELA)</p>
                  <p className="text-gray-500 mt-0.5">Generates 90% JPEG re-quantization error map to locate spliced or inpainted pixels.</p>
                </div>
              </div>

              <div className="flex items-start space-x-2.5">
                <div className="h-2 w-2 rounded-full bg-purple-500 mt-1.5 shrink-0" />
                <div>
                  <p className="font-bold text-dark">GAN & Diffusion Fingerprint</p>
                  <p className="text-gray-500 mt-0.5">Detects subtle frequency artifacts produced by Midjourney v5/v6, SDXL, and DALL-E 3.</p>
                </div>
              </div>

              <div className="flex items-start space-x-2.5">
                <div className="h-2 w-2 rounded-full bg-purple-500 mt-1.5 shrink-0" />
                <div>
                  <p className="font-bold text-dark">EXIF Sensor Profile Validation</p>
                  <p className="text-gray-500 mt-0.5">Checks for camera hardware tags (Make/Model) vs AI generator software stamps.</p>
                </div>
              </div>
            </div>
          </div>

          <div className="glass-card p-3.5 sm:p-5 bg-gradient-to-br from-purple-50/50 to-white border-purple-100">
            <p className="text-[11px] sm:text-xs font-bold text-purple-900 mb-0.5 sm:mb-1">Forensics Tip</p>
            <p className="text-[10px] sm:text-[11px] text-purple-700 leading-relaxed">
              For best accuracy, upload uncompressed original images directly from source cameras or platforms without resizing.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
